journey
    title Life cycle of 3d model
    section Creation of 3d model
      Idea is known: 7: 3d modeler
      3d model is shaped and formed: 5: 3d modeler
      Material is placed on model: 1: 3d modeler
      Model is exported: 3: 3d modeler
    section Use of python program
        File is plugged into the program: 8: Gameplay designer 
        File is transfered to correct format: 7: Python Program
    section Use of 3d model
      Troubleshoot for any errors in the model during transfer: 1: Gameplay designer
      3d model is imported: 2 : Gameplay designer
      3d model is programmed for use: 5: Gameplay designer